-- TREASURE HUNTER DATABASE
-- این فایل را کامل داخل Supabase -> SQL Editor اجرا کن.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text,
  coins bigint not null default 0,
  distance_m double precision not null default 0,
  treasures_count integer not null default 0,
  total_earned bigint not null default 0,
  theme text not null default 'dark',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  center_lat double precision not null,
  center_lon double precision not null,
  cashout_radius_m double precision not null default 250,
  seed bigint not null,
  treasures_found integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.treasures (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sequence integer not null,
  latitude double precision not null,
  longitude double precision not null,
  radius_m double precision not null default 38,
  reward integer not null default 50,
  found boolean not null default false,
  found_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id,sequence)
);

create index if not exists treasures_user_idx
on public.treasures(user_id,found,sequence);

alter table public.profiles enable row level security;
alter table public.game_state enable row level security;
alter table public.treasures enable row level security;

grant select,insert,update on public.profiles to authenticated;
grant select,insert,update on public.game_state to authenticated;
grant select,insert,update on public.treasures to authenticated;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using ((select auth.uid())=id);

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles
for insert to authenticated
with check ((select auth.uid())=id);

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
for update to authenticated
using ((select auth.uid())=id)
with check ((select auth.uid())=id);

drop policy if exists game_select on public.game_state;
create policy game_select on public.game_state
for select to authenticated
using ((select auth.uid())=user_id);

drop policy if exists game_insert on public.game_state;
create policy game_insert on public.game_state
for insert to authenticated
with check ((select auth.uid())=user_id);

drop policy if exists game_update on public.game_state;
create policy game_update on public.game_state
for update to authenticated
using ((select auth.uid())=user_id)
with check ((select auth.uid())=user_id);

drop policy if exists treasure_select on public.treasures;
create policy treasure_select on public.treasures
for select to authenticated
using ((select auth.uid())=user_id);

drop policy if exists treasure_insert on public.treasures;
create policy treasure_insert on public.treasures
for insert to authenticated
with check ((select auth.uid())=user_id);

drop policy if exists treasure_update on public.treasures;
create policy treasure_update on public.treasures
for update to authenticated
using ((select auth.uid())=user_id)
with check ((select auth.uid())=user_id);

-- ساخت پروفایل خودکار بعد از ثبت Auth
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  u text;
  real_email text;
begin
  u:=coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1));
  u:=regexp_replace(u,'[^A-Za-z0-9_]','','g');
  u:=left(u,24);

  if length(u)<3 then
    u:='hunter_'||left(replace(new.id::text,'-',''),15);
  end if;

  real_email:=new.raw_user_meta_data->>'real_email';

  insert into public.profiles(id,username,email)
  values(new.id,u,real_email)
  on conflict(id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- اضافه کردن مسافت
create or replace function public.add_distance(p_meters double precision)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if p_meters is null or p_meters<2 or p_meters>500 then
    return;
  end if;

  update public.profiles
  set distance_m=distance_m+p_meters,
      updated_at=now()
  where id=(select auth.uid());
end;
$$;

-- پیدا کردن گنج
create or replace function public.claim_treasure(
  p_treasure_id bigint,
  p_lat double precision,
  p_lon double precision
)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  t public.treasures%rowtype;
  d double precision;
begin
  select *
  into t
  from public.treasures
  where id=p_treasure_id
    and user_id=(select auth.uid())
  for update;

  if not found or t.found then
    raise exception 'Treasure unavailable';
  end if;

  d:=111320*sqrt(
    power(p_lat-t.latitude,2)+
    power(
      (p_lon-t.longitude)*cos(radians(p_lat)),
      2
    )
  );

  if d>t.radius_m+15 then
    raise exception 'Too far';
  end if;

  update public.treasures
  set found=true,found_at=now()
  where id=t.id;

  update public.profiles
  set treasures_count=treasures_count+1,
      total_earned=total_earned+t.reward,
      updated_at=now()
  where id=(select auth.uid());

  update public.game_state
  set treasures_found=treasures_found+1,
      updated_at=now()
  where user_id=(select auth.uid());
end;
$$;

-- تبدیل گنج به سکه
create or replace function public.cashout_treasures()
returns table(coins_added integer,treasures_converted integer)
language plpgsql
security definer
set search_path=''
as $$
declare
  c integer;
  amount integer;
begin
  select count(*)
  into c
  from public.treasures
  where user_id=(select auth.uid())
    and found=true;

  if c=0 then
    return query select 0,0;
    return;
  end if;

  select coalesce(sum(reward),0)::integer
  into amount
  from public.treasures
  where user_id=(select auth.uid())
    and found=true;

  update public.profiles
  set coins=coins+amount,
      treasures_count=greatest(0,treasures_count-c),
      updated_at=now()
  where id=(select auth.uid());

  delete from public.treasures
  where user_id=(select auth.uid())
    and found=true;

  return query select amount,c;
end;
$$;

-- رتبه‌بندی
create or replace function public.leaderboard()
returns table(
  username text,
  coins bigint,
  distance_m double precision,
  treasures_count integer
)
language sql
security definer
set search_path=''
as $$
  select
    p.username,
    p.coins,
    p.distance_m,
    p.treasures_count
  from public.profiles p
  order by p.coins desc,p.distance_m desc
  limit 20
$$;

grant execute on function public.add_distance(double precision) to authenticated;
grant execute on function public.claim_treasure(bigint,double precision,double precision) to authenticated;
grant execute on function public.cashout_treasures() to authenticated;
grant execute on function public.leaderboard() to authenticated;

revoke execute on function public.add_distance(double precision) from anon;
revoke execute on function public.claim_treasure(bigint,double precision,double precision) from anon;
revoke execute on function public.cashout_treasures() from anon;
revoke execute on function public.leaderboard() from anon;
